version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'api'
       MYSQL_USER: 'api'
       MYSQL_PASSWORD: 'q1w2e3r4'
       MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on: 
      - backend
    
